### ISSUE TITLE
Refreshing the board without reloading the whole page makes the status disappear

### ISSUE THREAD

**Issue by scaccoman** [rehangit/prstatus#13]
The "Refresh Now" button (appears in the top-right corner) in Jira allows you to refresh the board you're viewing without reloading the whole page. This, unfortunately, makes the PR Status disappear.

Suggested solution: Attach a click event listener on the "Refresh Now" button via the content script and re-sync the ticket's status

**Comment by rehangit** [comment]
There are event listener that monitors any changes to the subtree under id `#ghx-work`. The reason for using a deeper (than root) node is to keep refreshes to minimum. 

Adding a hook for Refresh now is a good suggestion. It should improve the situation. However the node does not always exist so we need to first monitor the root tree modifications for its addition which may be expensive.
