### ISSUE TITLE
Enable at jira.com

### ISSUE THREAD

**Issue by utapyngo** [rehangit/prstatus#17]
Could you please enable it at *.jira.com? Currently it is only enabled at *.atlassian.net:

https://github.com/rehangit/prstatus/blob/85ae86116c4e021c91b008cb2f2c5a9cada362e1/src/manifest.json

**Comment by rehangit** [comment]
What exactly is jira.com domain. There is no official mention of this on Atlassian website/docs. Kindly inform.
Adding the jira.com domain is simple enough but I am not sure what kind of html is used on such deployments. Can you confirm if it is regular atlassian jira site hosted on a different domain?

**Comment by utapyngo** [comment]
https://*.jira.com is listed here:
https://support.atlassian.com/organization-administration/docs/ip-addresses-and-domains-for-atlassian-cloud-products/

**Comment by rehangit** [comment]
I have released v1.0.4 with the requested fix. Please try and confirm.

**Comment by utapyngo** [comment]
Thank you, it works now!
