### ISSUE TITLE
Preserve settings across removal and reinstall.

### ISSUE THREAD

**Issue by rehangit** [rehangit/prstatus#4]
Currently the settings are lost if the user removes the extension and reinstalls for any reason. The old settings should be preserved and recovered when new install is made asking user for using or discarding old settings.

**Comment by scaccoman** [comment]
Chrome has a Cloud Storage API which could be used for this purpose: https://developer.chrome.com/apps/storage

_"When using storage.sync, the stored data will automatically be synced to any Chrome browser that the user is logged into, provided the user has sync enabled.

When Chrome is offline, Chrome stores the data locally. The next time the browser is online, Chrome syncs the data. Even if a user disables syncing, storage.sync will still work. In this case, it will behave identically to storage.local."_
